export { default as SvgArrowUp } from './arrowUp'
export { default as SvgArrowDown } from './arrowDown'
export { default as SvgMap } from './map'
export { default as SvgSpeed } from './speed'
export { default as SvgGeodata } from './geodata'
export { default as SvgChartBar } from './chartBar'
export { default as SvgBolt } from './bolt'
export { default as SvgUpdate } from './update'
